package org.teamchallenge.bookshop.enums;

public enum Category {
    ARCHITECTURE,BUSINESS_MARKETING,DESIGN,
    CULINARY,CINEMATOGRAPHY,ART,IT_PROGRAMMING,FASHION_AND_BEAUTY,
    PHILOSOPHY,PSYCHOLOGY,COMICS,LIFESTYLE,UKRAINIAN_AUTHORS
    }
